# Generated by Django 5.1.1 on 2024-11-04 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='books',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
