# Generated by Django 5.1.1 on 2024-10-05 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='post',
            new_name='book',
        ),
    ]
